server.port=${PORT:8080}
## MySQL Database Configuration
spring.datasource.url=jdbc:mysql://mysql-5d98fd4-artisan-cafe-backend.i.aivencloud.com:17498/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_BaLzNDWNBs7EKPs4VAD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# CloudPe S3 Credentials
cloud.s3.endpoint=https://s3.in-west3.purestore.io
cloud.s3.bucket=imageserver
cloud.s3.region=in-west3

cloud.s3.accessKey=803a7f41efcaabdeFPYG
cloud.s3.secretKey=Cj2dKT6BjoVfLZJwRG8PT3Ef5dfE9p9NtyfP7hGt